from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
import datetime
import threading
from OpenWeatherMap import OpenWeatherMap
import requests
from News_Feed import NewsFeed
from Spotify import Spotify



class Ui_MainWindow(object):
    def __init__(self):
        self.news_index = 0
        self.__news = NewsFeed().get_news()
        self.spotify = Spotify()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_time = QtWidgets.QFrame(self.centralwidget)
        self.frame_time.setGeometry(QtCore.QRect(60, 60, 431, 161))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.frame_time.setFont(font)
        self.frame_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_time.setObjectName("frame_time")
        self.splitter = QtWidgets.QSplitter(self.frame_time)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 381, 118))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.date_label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayoutTime = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayoutTime.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutTime.setObjectName("horizontalLayoutTime")
        self.hours = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.hours.setFont(font)
        self.hours.setScaledContents(False)
        self.hours.setObjectName("hours")
        self.horizontalLayoutTime.addWidget(self.hours)
        self.seconds = QtWidgets.QLabel(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.seconds.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.seconds.setFont(font)
        self.seconds.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.seconds.setObjectName("seconds")
        self.horizontalLayoutTime.addWidget(self.seconds)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutTime.addWidget(self.label)
        self.frame_time_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_time_2.setGeometry(QtCore.QRect(1440, 60, 461, 161))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.frame_time_2.setFont(font)
        self.frame_time_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_time_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_time_2.setObjectName("frame_time_2")
        self.wind_speed_label = QtWidgets.QLabel(self.frame_time_2)
        self.wind_speed_label.setGeometry(QtCore.QRect(190, 0, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.wind_speed_label.setFont(font)
        self.wind_speed_label.setObjectName("wind_speed_label")
        self.wind_speed_icon_label_2 = QtWidgets.QLabel(self.frame_time_2)
        self.wind_speed_icon_label_2.setGeometry(QtCore.QRect(140, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.wind_speed_icon_label_2.setFont(font)
        self.wind_speed_icon_label_2.setText("")
        self.wind_speed_icon_label_2.setPixmap(QtGui.QPixmap("img/wind.png"))
        self.wind_speed_icon_label_2.setScaledContents(True)
        self.wind_speed_icon_label_2.setObjectName("wind_speed_icon_label_2")
        self.sunrise_icon_label = QtWidgets.QLabel(self.frame_time_2)
        self.sunrise_icon_label.setGeometry(QtCore.QRect(270, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.sunrise_icon_label.setFont(font)
        self.sunrise_icon_label.setText("")
        self.sunrise_icon_label.setPixmap(QtGui.QPixmap("img/sunrise.png"))
        self.sunrise_icon_label.setScaledContents(True)
        self.sunrise_icon_label.setObjectName("sunrise_icon_label")
        self.sunrise_time_label = QtWidgets.QLabel(self.frame_time_2)
        self.sunrise_time_label.setGeometry(QtCore.QRect(320, 0, 79, 39))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.sunrise_time_label.setFont(font)
        self.sunrise_time_label.setScaledContents(False)
        self.sunrise_time_label.setObjectName("sunrise_time_label")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_time_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 40, 341, 79))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.weather_icon_label = QtWidgets.QLabel(self.layoutWidget1)
        self.weather_icon_label.setObjectName("weather_icon_label")
        self.horizontalLayout.addWidget(self.weather_icon_label)
        self.temp_label = QtWidgets.QLabel(self.layoutWidget1)
        self.temp_label.setObjectName("temp_label")
        self.horizontalLayout.addWidget(self.temp_label)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_time_2)
        self.label_5.setGeometry(QtCore.QRect(170, 120, 131, 39))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.feels_like_label = QtWidgets.QLabel(self.frame_time_2)
        self.feels_like_label.setGeometry(QtCore.QRect(310, 120, 49, 39))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.feels_like_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.feels_like_label.setFont(font)
        self.feels_like_label.setScaledContents(False)
        self.feels_like_label.setObjectName("feels_like_label")
        self.feels_like_C_label = QtWidgets.QLabel(self.frame_time_2)
        self.feels_like_C_label.setGeometry(QtCore.QRect(350, 120, 49, 39))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.feels_like_C_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.feels_like_C_label.setFont(font)
        self.feels_like_C_label.setScaledContents(False)
        self.feels_like_C_label.setObjectName("feels_like_C_label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1500, 260, 341, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.line_2.setPalette(palette)
        self.line_2.setStyleSheet("border-color: rgb(153, 153, 153);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1550, 240, 284, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1783, 30, 51, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1500, 50, 341, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.line_3.setPalette(palette)
        self.line_3.setStyleSheet("border-color: rgb(153, 153, 153);\n"
                                  "\n"
                                  "")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1499, 279, 361, 351))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(160, 0, 179, 286))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.forecast_day_label_1 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_day_label_1.setObjectName("forecast_day_label_1")
        self.horizontalLayout_2.addWidget(self.forecast_day_label_1)
        self.forecast_icon_label_1 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_icon_label_1.setMinimumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_1.setMaximumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_1.setText("")
        self.forecast_icon_label_1.setPixmap(QtGui.QPixmap("img/defaul_weather_icon.png"))
        self.forecast_icon_label_1.setScaledContents(True)
        self.forecast_icon_label_1.setObjectName("forecast_icon_label_1")
        self.horizontalLayout_2.addWidget(self.forecast_icon_label_1)
        self.forecast_temp_label_1 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_temp_label_1.setObjectName("forecast_temp_label_1")
        self.horizontalLayout_2.addWidget(self.forecast_temp_label_1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.forecast_day_label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_day_label_2.setObjectName("forecast_day_label_2")
        self.horizontalLayout_3.addWidget(self.forecast_day_label_2)
        self.forecast_icon_label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_icon_label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_2.setText("")
        self.forecast_icon_label_2.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/10d@2x.png"))
        self.forecast_icon_label_2.setObjectName("forecast_icon_label_2")
        self.horizontalLayout_3.addWidget(self.forecast_icon_label_2)
        self.forecast_temp_label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_temp_label_2.setObjectName("forecast_temp_label_2")
        self.horizontalLayout_3.addWidget(self.forecast_temp_label_2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.forecast_day_label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_day_label_3.setObjectName("forecast_day_label_3")
        self.horizontalLayout_4.addWidget(self.forecast_day_label_3)
        self.forecast_icon_label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_icon_label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_3.setMaximumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_3.setText("")
        self.forecast_icon_label_3.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/10d@2x.png"))
        self.forecast_icon_label_3.setObjectName("forecast_icon_label_3")
        self.horizontalLayout_4.addWidget(self.forecast_icon_label_3)
        self.forecast_temp_label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_temp_label_3.setObjectName("forecast_temp_label_3")
        self.horizontalLayout_4.addWidget(self.forecast_temp_label_3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.forecast_day_label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_day_label_4.setObjectName("forecast_day_label_4")
        self.horizontalLayout_5.addWidget(self.forecast_day_label_4)
        self.forecast_icon_label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_icon_label_4.setMinimumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_4.setText("")
        self.forecast_icon_label_4.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/10d@2x.png"))
        self.forecast_icon_label_4.setObjectName("forecast_icon_label_4")
        self.horizontalLayout_5.addWidget(self.forecast_icon_label_4)
        self.forecast_temp_label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_temp_label_4.setObjectName("forecast_temp_label_4")
        self.horizontalLayout_5.addWidget(self.forecast_temp_label_4)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.forecast_day_label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_day_label_5.setObjectName("forecast_day_label_5")
        self.horizontalLayout_6.addWidget(self.forecast_day_label_5)
        self.forecast_icon_label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_icon_label_5.setMinimumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_5.setMaximumSize(QtCore.QSize(50, 50))
        self.forecast_icon_label_5.setText("")
        self.forecast_icon_label_5.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/10d@2x.png"))
        self.forecast_icon_label_5.setObjectName("forecast_icon_label_5")
        self.horizontalLayout_6.addWidget(self.forecast_icon_label_5)
        self.forecast_temp_label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.forecast_temp_label_5.setObjectName("forecast_temp_label_5")
        self.horizontalLayout_6.addWidget(self.forecast_temp_label_5)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.frame_news_feed = QtWidgets.QFrame(self.centralwidget)
        self.frame_news_feed.setGeometry(QtCore.QRect(0, 819, 1920, 101))
        self.frame_news_feed.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.frame_news_feed.setFont(font)
        self.frame_news_feed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_news_feed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_news_feed.setObjectName("frame_news_feed")
        self.news_feed_label = QtWidgets.QLabel(self.frame_news_feed)
        self.news_feed_label.setGeometry(QtCore.QRect(0, 50, 1920, 50))
        self.news_feed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.news_feed_label.setObjectName("news_feed_label")
        self.news_feed_author_label = QtWidgets.QLabel(self.frame_news_feed)
        self.news_feed_author_label.setGeometry(QtCore.QRect(0, 20, 1920, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.news_feed_author_label.setFont(font)
        self.news_feed_author_label.setStyleSheet("color: rgb(170, 170, 170);")
        self.news_feed_author_label.setAlignment(QtCore.Qt.AlignCenter)
        self.news_feed_author_label.setObjectName("news_feed_author_label")
        self.spotify_image = QtWidgets.QLabel(self.centralwidget)
        self.spotify_image.setGeometry(QtCore.QRect(840, 60, 311, 321))
        self.spotify_image.setText("")
        self.spotify_image.setPixmap(QtGui.QPixmap("img/spotify_default.png"))
        self.spotify_image.setScaledContents(False)
        self.spotify_image.setObjectName("spotify_image")
        self.spotify_progressbar = QtWidgets.QSlider(self.centralwidget)
        self.spotify_progressbar.setGeometry(QtCore.QRect(840, 510, 291, 22))
        self.spotify_progressbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spotify_progressbar.setStyleSheet("QSlider::groove:horizontal {\n"
                                               "border: 1px solid #bbb;\n"
                                               "background: white;\n"
                                               "height: 10px;\n"
                                               "border-radius: 4px;\n"
                                               "}\n"
                                               "\n"
                                               "QSlider::sub-page:horizontal {\n"
                                               "background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
                                               "    stop: 0 #808080, stop: 1 #cfcfcf );\n"
                                               "background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
                                               "    stop: 0 #808080, stop: 1 #cfcfcf);\n"
                                               "border: 1px solid #777;\n"
                                               "height: 10px;\n"
                                               "border-radius: 4px;\n"
                                               "}\n"
                                               "\n"
                                               "QSlider::add-page:horizontal {\n"
                                               "background: #000;\n"
                                               "border: 1px solid #777;\n"
                                               "height: 10px;\n"
                                               "border-radius: 4px;\n"
                                               "}\n"
                                               "\n"
                                               "QSlider::handle:horizontal {\n"
                                               "background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
                                               "    stop:0 #cfcfcf, stop:1 #d6d6d6);\n"
                                               "border: 1px hidden #777;\n"
                                               "width: 13px;\n"
                                               "margin-top: -2px;\n"
                                               "margin-bottom: -2px;\n"
                                               "border-radius: 5px;\n"
                                               "}\n"
                                               "\n"
                                               "\n"
                                               "")
        self.spotify_progressbar.setMaximum(100)
        self.spotify_progressbar.setProperty("value", 60)
        self.spotify_progressbar.setOrientation(QtCore.Qt.Horizontal)
        self.spotify_progressbar.setInvertedAppearance(False)
        self.spotify_progressbar.setInvertedControls(False)
        self.spotify_progressbar.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.spotify_progressbar.setObjectName("spotify_progressbar")
        self.spotify_device_label = QtWidgets.QLabel(self.centralwidget)
        self.spotify_device_label.setGeometry(QtCore.QRect(840, 540, 218, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spotify_device_label.setFont(font)
        self.spotify_device_label.setObjectName("spotify_progress_duration_label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(840, 380, 260, 141))
        self.widget.setObjectName("widget")
        self.spotify_text_layout = QtWidgets.QFormLayout(self.widget)
        self.spotify_text_layout.setContentsMargins(0, 0, 0, 0)
        self.spotify_text_layout.setHorizontalSpacing(15)
        self.spotify_text_layout.setObjectName("spotify_text_layout")
        self.music_icon = QtWidgets.QLabel(self.widget)
        self.music_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.music_icon.setText("")
        self.music_icon.setPixmap(QtGui.QPixmap("img/music-icon.png"))
        self.music_icon.setScaledContents(True)
        self.music_icon.setObjectName("music_icon")
        self.spotify_text_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.music_icon)
        self.spotify_titel_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spotify_titel_label.setFont(font)
        self.spotify_titel_label.setObjectName("spotify_titel_label")
        self.spotify_text_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spotify_titel_label)
        self.artist_icon = QtWidgets.QLabel(self.widget)
        self.artist_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.artist_icon.setText("")
        self.artist_icon.setPixmap(QtGui.QPixmap("img/artist_icon.png"))
        self.artist_icon.setScaledContents(True)
        self.artist_icon.setObjectName("artist_icon")
        self.spotify_text_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.artist_icon)
        self.spotify_artists_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spotify_artists_label.setFont(font)
        self.spotify_artists_label.setObjectName("spotify_artists_label")
        self.spotify_text_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spotify_artists_label)
        self.folder_icon = QtWidgets.QLabel(self.widget)
        self.folder_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.folder_icon.setText("")
        self.folder_icon.setPixmap(QtGui.QPixmap("img/folder_icon.png"))
        self.folder_icon.setScaledContents(True)
        self.folder_icon.setObjectName("folder_icon")
        self.spotify_text_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.folder_icon)
        self.spotify_album_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spotify_album_label.setFont(font)
        self.spotify_album_label.setObjectName("spotify_album_label")
        self.spotify_text_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spotify_album_label)
        self.play_stop_icon = QtWidgets.QLabel(self.widget)
        self.play_stop_icon.setMinimumSize(QtCore.QSize(25, 25))
        self.play_stop_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.play_stop_icon.setText("")
        self.play_stop_icon.setPixmap(QtGui.QPixmap("img/pause_icon.png"))
        self.play_stop_icon.setScaledContents(True)
        self.play_stop_icon.setObjectName("play_stop_icon")
        self.spotify_text_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.play_stop_icon)
        self.spotify_progress_duration_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spotify_progress_duration_label.setFont(font)
        self.spotify_progress_duration_label.setObjectName("spotify_progress_duration_label")
        self.spotify_text_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spotify_progress_duration_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # ---manuel---
        self.update_date()
        self.update_time(0)
        self.update_weather()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.date_label.setText(_translate("MainWindow", "Samstag, 17. April 2021"))
        self.hours.setText(_translate("MainWindow", "20:45"))
        self.seconds.setText(_translate("MainWindow", "30"))
        self.wind_speed_label.setText(_translate("MainWindow", "0.5"))
        self.sunrise_time_label.setText(_translate("MainWindow", "20:30"))
        self.weather_icon_label.setText(_translate("MainWindow", "Icon"))
        self.temp_label.setText(_translate("MainWindow", "22.0"))
        self.label_4.setText(_translate("MainWindow", "°C"))
        self.label_5.setText(_translate("MainWindow", "Feels like"))
        self.feels_like_label.setText(_translate("MainWindow", "14"))
        self.feels_like_C_label.setText(_translate("MainWindow", "°C"))
        self.label_2.setText(_translate("MainWindow", "WEATHER FORECAST ESSEN,DE"))
        self.label_3.setText(_translate("MainWindow", "Essen"))
        self.forecast_day_label_1.setText(_translate("MainWindow", "Mon"))
        self.forecast_temp_label_1.setText(_translate("MainWindow", "13.5"))
        self.label_6.setText(_translate("MainWindow", "°C"))
        self.forecast_day_label_2.setText(_translate("MainWindow", "Mon"))
        self.forecast_temp_label_2.setText(_translate("MainWindow", "13.5"))
        self.label_7.setText(_translate("MainWindow", "°C"))
        self.forecast_day_label_3.setText(_translate("MainWindow", "Mon"))
        self.forecast_temp_label_3.setText(_translate("MainWindow", "13.5"))
        self.label_8.setText(_translate("MainWindow", "°C"))
        self.forecast_day_label_4.setText(_translate("MainWindow", "Mon"))
        self.forecast_temp_label_4.setText(_translate("MainWindow", "13.5"))
        self.label_9.setText(_translate("MainWindow", "°C"))
        self.forecast_day_label_5.setText(_translate("MainWindow", "Mon"))
        self.forecast_temp_label_5.setText(_translate("MainWindow", "13.5"))
        self.label_10.setText(_translate("MainWindow", "°C"))
        self.news_feed_label.setText(_translate("MainWindow",
                                                "Indiens Corona-Zahlen explodieren: Lauterbach warnt vor „Katastrophe“ durch Doppelmutante - Briten reagieren"))
        self.news_feed_author_label.setText(_translate("MainWindow", "DER SPIEGEL"))
        self.spotify_device_label.setText(_translate("MainWindow", "DESKTOP-N856B1S"))
        self.spotify_titel_label.setText(_translate("MainWindow", "Auf & Ab"))
        self.spotify_artists_label.setText(_translate("MainWindow", "Montez"))
        self.spotify_album_label.setText(_translate("MainWindow", "Album"))
        self.spotify_progress_duration_label.setText(_translate("MainWindow", "10:42 / 12:53"))

    def update_time(self, n):

        self.update_time_labels()

        time_thread = threading.Timer(1.0, lambda: self.update_time(n + 1))
        time_thread.daemon = True
        time_thread.start()

        if n >= 3600:
            update_weather_thread = threading.Thread(target=self.update_weather())
            update_weather_thread.daemon = True
            update_weather_thread.start()
            n = 0
            print("updating weather...")
        if n % 8 == 0:
            news_feed_thread = threading.Thread(target=self.update_news_feed())
            news_feed_thread.daemon = True
            news_feed_thread.start()

        if n % 2 == 0:
            spotify_thread = threading.Thread(target=self.update_spotify())
            spotify_thread.daemon = True
            spotify_thread.start()

        time = datetime.datetime.now()
        if self.date_label != datetime.datetime.today().date():
            update_date_thread = threading.Thread(target=self.update_date())
            update_date_thread.daemon = True
            update_date_thread.start()

    def update_time_labels(self):
        time = datetime.datetime.now()
        self.hours.setText(f"{time.strftime('%H')}:{time.strftime('%M')}")
        self.seconds.setText(time.strftime("%S"))

    def update_date(self):
        self.date_label.setText("")
        self.date = datetime.datetime.today().date()
        date = datetime.datetime.now()
        self.date_label.setText(
            f"{date.strftime('%A')}, {date.strftime('%d')}. {date.strftime('%B')} {date.strftime('%Y')}")

    def update_weather(self):
        weather = OpenWeatherMap().get_weather_data()
        self.temp_label.setText(str(round(weather["temp"], 1)))
        self.sunrise_time_label.setText(
            datetime.datetime.fromtimestamp(weather["sunrise"]).strftime("%H") + ":" + datetime.datetime.fromtimestamp(
                weather["sunrise"]).strftime("%M"))
        self.wind_speed_label.setText(str(round(weather["wind_speed"], 1)))
        weather_icon = QImage()
        weather_icon.loadFromData(requests.get(f"http://openweathermap.org/img/wn/{weather['icon']}@2x.png").content)
        self.weather_icon_label.setPixmap(QPixmap(weather_icon))
        self.update_forecast()
        self.__news = NewsFeed().get_news()

        print("weather has been updated")

    def update_forecast(self):
        forecasts = OpenWeatherMap().get_forecast()
        self.forecast_day_label_1.setText(str(datetime.datetime.fromtimestamp(forecasts[0].dt).strftime("%a")))
        forecast_icon_1 = QImage()
        forecast_icon_1.loadFromData(
            requests.get(f"http://openweathermap.org/img/wn/{forecasts[0].icon}@2x.png").content)
        self.forecast_icon_label_1.setPixmap(QPixmap(forecast_icon_1))
        self.forecast_icon_label_1.setScaledContents(True)
        self.forecast_temp_label_1.setText(forecasts[0].temp)

        self.forecast_day_label_2.setText(str(datetime.datetime.fromtimestamp(forecasts[1].dt).strftime("%a")))
        forecast_icon_2 = QImage()
        forecast_icon_2.loadFromData(
            requests.get(f"http://openweathermap.org/img/wn/{forecasts[1].icon}@2x.png").content)
        self.forecast_icon_label_2.setPixmap(QPixmap(forecast_icon_2))
        self.forecast_icon_label_2.setScaledContents(True)
        self.forecast_temp_label_2.setText(forecasts[1].temp)

        self.forecast_day_label_3.setText(str(datetime.datetime.fromtimestamp(forecasts[2].dt).strftime("%a")))
        forecast_icon_3 = QImage()
        forecast_icon_3.loadFromData(
            requests.get(f"http://openweathermap.org/img/wn/{forecasts[2].icon}@2x.png").content)
        self.forecast_icon_label_3.setPixmap(QPixmap(forecast_icon_3))
        self.forecast_icon_label_3.setScaledContents(True)
        self.forecast_temp_label_3.setText(forecasts[2].temp)

        self.forecast_day_label_4.setText(str(datetime.datetime.fromtimestamp(forecasts[3].dt).strftime("%a")))
        forecast_icon_4 = QImage()
        forecast_icon_4.loadFromData(
            requests.get(f"http://openweathermap.org/img/wn/{forecasts[3].icon}@2x.png").content)
        self.forecast_icon_label_4.setPixmap(QPixmap(forecast_icon_4))
        self.forecast_icon_label_4.setScaledContents(True)
        self.forecast_temp_label_4.setText(forecasts[3].temp)

        self.forecast_day_label_5.setText(str(datetime.datetime.fromtimestamp(forecasts[3].dt).strftime("%a")))
        forecast_icon_5 = QImage()
        forecast_icon_5.loadFromData(
            requests.get(f"http://openweathermap.org/img/wn/{forecasts[4].icon}@2x.png").content)
        self.forecast_icon_label_5.setPixmap(QPixmap(forecast_icon_5))
        self.forecast_icon_label_5.setScaledContents(True)
        self.forecast_temp_label_5.setText(forecasts[4].temp)

    def update_news_feed(self):
        if self.news_index >= len(self.__news):
            self.news_index = 0
        self.news_feed_author_label.setText(self.__news[self.news_index][1])
        self.news_feed_label.setText(self.__news[self.news_index][0])
        self.news_index += 1

    def update_spotify(self):
        data = self.spotify.get_data()
        if data:
            self.spotify_titel_label.setText(data["name"])
            self.spotify_album_label.setText(data["album_name"])
            self.spotify_device_label.setText(data["device"])
            self.spotify_artists_label.setText(", ".join(data["artist"]))
            duration = data["duration"]
            progress = data["progress"]
            self.spotify_progress_duration_label.setText(
                f"{progress['minutes']:02}:{progress['seconds']:02} / {duration['minutes']:02}:{duration['seconds']:02}")

            if data["is_playing"]:
                self.play_stop_icon.setPixmap(QtGui.QPixmap("img/play_icon.png"))
            else:
                self.play_stop_icon.setPixmap(QtGui.QPixmap("img/pause_icon.png"))

            spotify_image = QImage()
            spotify_image.loadFromData(requests.get(data["image"]).content)
            self.spotify_image.setPixmap(QPixmap(spotify_image))

            self.spotify_progressbar.setValue(data["progress_percentage"])

        else:
            print("no Spotify data")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec_())
